---
title: "Self Evaluation L01 Review"
subtitle: |
  | Data Science 2 with R 
  | STAT 301-2
author: "Owen Broadwater"
pagetitle: "Self Evaluation PQ2 Owen Broadwater"
date: today

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 4
    toc-location: left
    embed-resources: true
    code-fold: false
    link-external-newwindow: true

execute:
  warning: false
  error: true

from: markdown+emoji
reference-location: margin
citation-location: margin 
---

::: {.callout-tip icon="false"}
## Github Repo Link

[Broadwater Github](https://github.com/stat301-3-2026-spring/l01-review-obroadwater.git)
:::

## Overview

The goal of this lab is to review machine learning/predictive modeling vocabulary and concepts covered in Data Science 2 with R (STAT 301-2).

## Questions

When completing the following questions ensure your solutions are neatly formatted and clearly indicated. Consider including diagrams/images in some of your solutions, if it helps to make things easier to describe/discuss.

### Question 1

Provide a brief outline/overview of the steps involved in a supervised machine learning process. Could provide this as a bulleted list. 

::: {.callout-tip icon="false"}
## Solution

- Data cleaning
- Data processing
- Feature Engineering
- Model Tuning
- Cross Validation
- Model Selection
- Model Fitting
- Evaluation of Performance

:::
### Self Evaluation

::: {.callout-important icon="false"}

## Score 
3

## Explanation

My steps weren't incorrect but reflected a pared down version of the actual process. For instance, I left out steps such as data collection and resampling techniques. This occurred because I was struggling to transfer the entire machine learning process into a condensed list, so I didn't make great decisions about which steps were important to include.

## Updated solution

*Only required if a 3 or less is scored on the question.*

- Data collection
- Data cleaning
- Data processing
- Splitting of the data
- Setup of resampling technique
- Feature Engineering, recipe building
- Model Tuning
- Cross Validation
- Selection of the best model
- Fitting the best model to the whole training set
- Evaluation of Performance on the testing set

:::

### Question 2

Explain the difference between supervised and unsupervised learning.

::: {.callout-tip icon="false"}
## Solution

Supervised learning uses labeled data and a desired outcome and relies on user assumptions such as choosing which predictors to use.

Unsupervised learning looks at unlabeled data to create a general idea of the data structures, extracting information even though there is no specifically desired outcome.

:::
### Self Evaluation

::: {.callout-important icon="false"}

## Score 
4

## Explanation

My response was correct, although I drew a slightly misleading line around the role of labelled vs. unlabeled data which isn't always a difference in supervised/unsupervised learning. Supervised learning generally does require labeled data but unsupervised learning can use both.

:::

### Question 3 

In general, we can classify a model by its purpose into 1 of the 3 categories below. Provide a brief description of the goals of these model classes.

#### Descriptive Models 

::: {.callout-tip icon="false"}
## Solution

Describe or emphasize characteristics of a dataset, such as a key trend. It summarizes the data.

:::
### Self Evaluation

::: {.callout-important icon="false"}

## Score 
4

## Explanation

My answer is correct, I could have included that the goal is to visually emphasize a trend of the data.

:::

#### Inferential Models

::: {.callout-tip icon="false"}
## Solution

Weigh in on a hypothesis that is being tested, for instance determining if there is a causal effect between two variables.

:::
### Self Evaluation

::: {.callout-important icon="false"}

## Score 
5

## Explanation

My answer was correct, in my words.

:::

#### Predictive Models

::: {.callout-tip icon="false"}
## Solution

Produce accurate predictions for new data.

:::
### Self Evaluation

::: {.callout-important icon="false"}

## Score 
4

## Explanation

I left out that the goal is produce the *most* accurate prediction possible, as well as that their is a outcome variable involved.

:::

### Question 4 

We can further describe/classify predictive models by how they were derived or developed as being either mechanistic or empirically driven. 

#### Part (a)

What does it mean to be a mechanistic model?

::: {.callout-tip icon="false"}
## Solution

Mechanistic models build a representation of a system based on known equations or laws, to explain why observed patterns occur.

:::
### Self Evaluation

::: {.callout-important icon="false"}

## Score 
4

## Explanation

My answer was correct, although it left out a discussion of the benefits of mechanistic models, such as fast computation.

:::

#### Part (b)

What does it mean to be an empirically driven model?

::: {.callout-tip icon="false"}
## Solution

Empirical models build a representation from the data, using the data's patterns and observations to build an equation, demonstrating how a system behaves.

:::
### Self Evaluation

::: {.callout-important icon="false"}

## Score 
4

## Explanation

Similar to my answer on mechanistic models, I did not discuss the benefits of empirical models, namely flexibility at the expense of slower computation time.


:::

#### Part (c)

How does the mechanistic and empirically driven model terminology relate to the parametric and nonparametric model terminology? 

::: {.callout-tip icon="false"}
## Solution

Parametric models are based on an assumed equation like linear regression, much like how mechanistic models impose preconceived equations. Nonparametric models do not make any assumptions about equations, similar to how empirical models derive their equations from the data.

:::
### Self Evaluation

::: {.callout-important icon="false"}

## Score 
5

## Explanation

My answer is correct, explains the linkage between terms.

:::

#### Part (d)

In general, is a mechanistic or empirically driven model easier to interpret? Explain.

::: {.callout-tip icon="false"}
## Solution

Mechanistic drive models are usually easier to interpret because they use equation forms that are already known and established. Conversely empirically driven models create new equations that are harder to understand.

:::
### Self Evaluation

::: {.callout-important icon="false"}

## Score 
5

## Explanation

My answer is correct and very similar to the solution.

:::

#### Part (e)

How does mechanistic and empirically driven model terminology relate to the idea of model flexibility? That is, which would be more or less flexible than the other.

::: {.callout-tip icon="false"}
## Solution

Empirically drive models are more flexible because the derivation of equations from the data allows for a much greater range of equation forms than mechanistic models that only draw upon known or established equation forms.

:::
### Self Evaluation

::: {.callout-important icon="false"}

## Score 
5

## Explanation

I correctly identified that the key reason for the flexibility of empirically driven models is their lack of restrictions on equations.

:::

#### Part (f)

Describe the bias-variance trade-off when considering the use of a mechanistic or empirically driven model. 

::: {.callout-tip icon="false"}
## Solution

Mechanistic models tend to have lower variance and higher bias due to its simple model that tends to underfit the data, whereas empirical models tend to have higher variance and lower bias due to its compleixity that tends to overfit the data.

:::
### Self Evaluation

::: {.callout-important icon="false"}

## Score 
4

## Explanation

I captured the basic trends of the bias-variance trade-off, but didn't quite explain the conceptual underpinnings of that trend, that mechanistic models lack of flexibility makes underfitting likely, for instance.


:::

### Question 5 

Explain the difference between a regression and classification machine learning (ML) problems.

::: {.callout-tip icon="false"}
## Solution

Regression ML problems are used to look at continuous outcomes, such as housing prices, while classification ML problems are used to look at discrete outcomes like whether someone has a disease.

:::
### Self Evaluation

::: {.callout-important icon="false"}

## Score 
5

## Explanation

I correctly identified the difference between regression and classification, and gave examples of their use.

:::

### Question 6 

When splitting the data, why is it useful to stratify by the outcome/target variable? 

::: {.callout-tip icon="false"}
## Solution

Stratifying by the target variable ensures that relative proportions of the target are present in both training and testing set, preventing severe class imbalance between sets.

:::
### Self Evaluation

::: {.callout-important icon="false"}

## Score 
4

## Explanation

I identified the benefits of stratifying by the outcome variable, although I didn't fully explain the problems that arise from a training set that doesn't capture the distribution of the overall data's outcome variable -- overfitting or underfitting, thus poor predictive power.


:::

### Question 7 

Briefly describe how v-fold cross validation with repeats is used to estimate test RMSE. Also provide an explanation of why we use it. 

::: {.callout-tip icon="false"}
## Solution

V-fold cross validation splits the training data set into v number of folds then take turns using one as the evaluation set and all other folds as the training set for a model. This helps combat overfitting by averaging the performance of a model over many different sets of training and evaluation, before using the final testing set. This can also be used to compare the performances of various model types and parameter sets.

:::
### Self Evaluation

::: {.callout-important icon="false"}

## Score 
3

## Explanation

My answer is correct but incomplete. I failed to discuss the role of repeats and how the estimates are combined. I also did not discuss the benefits of v-fold cross validation on bias and variance.

## Updated solution

*Only required if a 3 or less is scored on the question.*

V-fold cross validation splits the training data set into v number of folds then take turns using one as the evaluation set and all other folds as the training set for a model. This happens r times, and the estimates are then averaged to produce a final estimate of a metric such as RMSE.

This helps combat overfitting by averaging the performance of a model over many different sets of training and evaluation, before using the final testing set. This reduces the effects of random varaition and bias from the distinct samples, giving a better estimate of performance. Thus comparison of various model types and parameter sets is better, as the RMSE was not influenced by different splits to a problematic degree.

:::

### Question 8

When might we use a bootstrap resampling procedure instead of v-fold cross validation to estimate test RMSE?

::: {.callout-tip icon="false"}
## Solution

Bootstrap resampling might be used in cases of small data sets, where there isn't enough distinct observations to create representative folds in v-fold cross validation.

:::
### Self Evaluation

::: {.callout-important icon="false"}

## Score 
4

## Explanation

I identified the benefits of bootstrapping in small data sets, but did not mention that bootstrap resampling leads to low variance in RMSE.

:::

### Question 9 

Briefly describe model tuning and why we use it.

::: {.callout-tip icon="false"}
## Solution

Model tuning involves changing the parameters of a model and testing many different combinations of those parameters. The parameters change the model's performance so finding the best performing parameter set improves the performance of the model without changing anything else.

:::
### Self Evaluation

::: {.callout-important icon="false"}

## Score 
4

## Explanation

I explained how model tuning is used within the machine learning process but didn't fully articulate that each set of tuning parameters yields a different model with different performance.
:::

### Question 10 

What are two common performance metrics when dealing with a regression ML problem?

::: {.callout-tip icon="false"}
## Solution

Two common performance metrics for regression ML problems are RMSE and MAE.

:::
### Self Evaluation

::: {.callout-important icon="false"}

## Score 
5

## Explanation

I identified 2 very common metrics for regression ML.

:::

What are two common performance metrics when dealing with a classification ML problem?

::: {.callout-tip icon="false"}
## Solution

Two common performance metrics for classification ML problems are Accuracy and AUC-ROC.

:::
### Self Evaluation

::: {.callout-important icon="false"}

## Score 
5

## Explanation

I identified 2 very common metrics for classification ML.
:::

### Question 11

Classify each question/problem below as either prediction or inferential. Explain your reasoning for each.

A company with a subscription based service (for example Netflix, Disney+, New York Times, etc) has data concerning customer interactions with a them, including features like the number of customer service calls, quality of service calls, subscription length, engagement with the service, discounted service, etc. They are interested in two questions:

1. Does a high number of service calls impact a customer's likelihood of churn in the next month (leave the company/drop the service)?

::: {.callout-tip icon="false"}
## Solution

Inferential: there is a hypothesis about a very specific relationship between variables, the question seeks to determine the why behind a customer's likelihood of churn.

:::
### Self Evaluation

::: {.callout-important icon="false"}

## Score 
4

## Explanation

I understood that it was an inferential problem, and explained how I knew, but I didn't identify the specific predictor variable (number of service calls).

:::

2. How likely is it that a customer will churn in the next month (leave the company/drop the service)?

::: {.callout-tip icon="false"}
## Solution

Predictive: there is no hypothesis or asking of why, the question seeks to use previous data to make a prediction about a future result.

:::
### Self Evaluation

::: {.callout-important icon="false"}

## Score 
5

## Explanation

I correctly identified that it was a predictive problem and explained how I knew.
:::

